kakao:
  KAKAO_CLIENT_ID: 7fefee8d2ced21539116c8229ac33123
  KAKAO_REDIRECT_URI: http://localhost:3000/login/oauth2/callback/kakao
  KAKAO_CLIENT_SECRET: AygPZ8n4t7sSd2iTpjkFFvKEI8ugcAE1
  KAKAO_TOKEN_URI: https://kauth.kakao.com/oauth/token
  KAKAO_USER_INFO_URI: https://kapi.kakao.com/v2/user/me

spring:
    datasource:
      url: jdbc:h2:tcp://localhost/~/welcome
      username: sa
      password: 1234
      driver-class-name: org.h2.Driver
    jpa:
      defer-datasource-initialization: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          # show_sql: true
          format_sql: true